### ISSUE TITLE
Error when opening :History in fzf

### ISSUE THREAD

**Issue by bbtdev** [fgrsnau/ncm2-otherbuf#5]
It does not happen always, though, I can't reproduce it. It happens sometimes.
```
[ncm2_otherbuf@yarp] error caught in notification handler 'on_warmup [{'filepath': '', 'source': {'subscope_enable': 0, 'early_cache': 0, 'name': 'otherbuf', 'priority': 4, 'mark': 'o', 'on_warmup': 'ncm2_otherbuf#on_warm
up', 'ready': 1, 'enable': 1, 'auto_popup': 1, 'on_complete': 'ncm2_otherbuf#on_complete'}, 'scope_match': '', 'scope_level': 1, 'lnum': 1, 'bufnr': 71, 'changedtick': 2, 'typed': '', 'ccol': 1, 'filetype': '', 'curpos': 
[0, 1, 1, 0, 1], 'tick': [[0, 1, 1], 26], 'early_cache': False, 'context_id': 1049, 'scope': '', 'bcol': 1}]'                                                                                                                
[ncm2_otherbuf@yarp] Traceback (most recent call last):                                                                                                                                                                      
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/share/nvim/plugged/nvim-yarp/pythonx/yarp.py", line 30, in on_notification                                                                                                  
[ncm2_otherbuf@yarp]     getattr(module_obj, method)(*args)                                                                                                                                                                  
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/share/nvim/plugged/ncm2-otherbuf/pythonx/ncm2_otherbuf.py", line 84, in on_warmup                                                                                           
[ncm2_otherbuf@yarp]     self.update()                                                                                                                                                                                       
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/share/nvim/plugged/ncm2-otherbuf/pythonx/ncm2_otherbuf.py", line 42, in update                                                                                              
[ncm2_otherbuf@yarp]     self.buffers[buf.number] = self.rescan_buffer(buf)                                                                                                                                                  
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/share/nvim/plugged/ncm2-otherbuf/pythonx/ncm2_otherbuf.py", line 55, in rescan_buffer                                                                                       
[ncm2_otherbuf@yarp]     for line in buf:                                                                                                                                                                                    
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/lib/python3.6/site-packages/pynvim/api/buffer.py", line 75, in __iter__                                                                                                     
[ncm2_otherbuf@yarp]     lines = self[:]                                                                                                                                                                                     
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/lib/python3.6/site-packages/pynvim/api/buffer.py", line 48, in __getitem__                                                                                                  
[ncm2_otherbuf@yarp]     return self.request('nvim_buf_get_lines', start, end, False)                                                                                                                                        
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/lib/python3.6/site-packages/pynvim/api/common.py", line 51, in request                                                                                                      
[ncm2_otherbuf@yarp]     return self._session.request(name, self, *args, **kwargs)                                                                                                                                           
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request                                                                                                       
[ncm2_otherbuf@yarp]     res = self._session.request(name, *args, **kwargs)                                                                                                                                                  
[ncm2_otherbuf@yarp]   File "/home/bogdan/.local/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request                                                                                            
[ncm2_otherbuf@yarp]     raise self.error_wrapper(err)                                                                                                                                                                       
[ncm2_otherbuf@yarp] pynvim.api.nvim.NvimError: b'Invalid buffer id'  
```

**Comment by fgrsnau** [comment]
Thanks, I still have to investigate what is going on exactly.
